[package]
name = "leddy"
version = "0.1.0"
authors = ["Hanna Reitz <hanna@xanclic.moe>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hidapi = "1.2.1"
rand = "0.7.3"
rustfft = "3.0"
